### PR TITLE
Stable/3.3.1

### PR DESCRIPTION
**Pull request by pvicente**
Hi @jacmoe,

This PR includes some fixes for your library which is already in conan-center.
- Fixes library sources and recipe licenses. The license for sources is **BSD 3-Clause**, please fix it also in [Bintray properties](https://bintray.com/jacmoe/Conan/Assimp%3Ajacmoe/3.3.1%3Astable)
- Fixes fPIC for Windows

Please create stable/3.3.1 branch in your repo based on these changes. I'm going to submit another version 4.1.0 of this library so you can keep both version in different branches.

CI jobs will only submit artifacts to bintray from stable branches.

### CODE REVIEW

**Comment by shearer12345** [comment]
@pvicente these look great. Thanks for putting the time into them.

@jacmoe do you have a chance to merge these soon? That would be totally awesome

**Comment by pvicente** [comment]
@shearer12345  there is also https://github.com/jacmoe/conan-assimp/pull/8 for version ```4.1.0``` it would be great if @jacmoe merges it too.

**Comment by jacmoe** [comment]
Yes I agree ;-)
Been busy with the family, but I am going to be on it this week :-D

**Comment by shearer12345** [comment]
Awesome. That's great news :)

--
John Shearer

**Comment by danimtb** [comment]
any update on this @jacmoe?

The Conan team would like to have this changes available in the official conan package.

Thanks!

**Comment by jacmoe** [comment]
Uhm, whoops - yes :smile: 
After two times the flu and a new computer I am getting ready to do this!
Thank you for your patience.
I am very close to having set my new machine up the way I want it, so ...

**Comment by jacmoe** [comment]
I merged this directly into stable/3.3.1 :)
Github is apparently not intelligent enough to recognize it, or I am not intelligent enough to do it properly?

**Comment by danimtb** [comment]
Yeah, maybe it didn't catch the way you did the merge. But dont worry, I see the commits there.

Thank you so much @jacmoe!

**Pull request closed without merging**
